### ISSUE TITLE
Cannot find module 'lodash.repeat'

### ISSUE THREAD

**Issue by rbaprado** [ChrisWren/grunt-node-inspector#27]
Tried installing on Windows, iojs:

Error: Cannot find module 'lodash.repeat'
    at Function.Module._resolveFilename (module.js:332:15)
    at Function.Module._load (module.js:282:25)
    at Module.require (module.js:361:17)
    at require (module.js:380:17)
    at Object.<anonymous> (D:\buzz\Projetos\mobtag_lab\node_modules\grunt-node-inspector\node_modules\node-inspector\nod
e_modules\v8-profiler\node_modules\node-pre-gyp\node_modules\npmlog\node_modules\gauge\node_modules\lodash.pad\node_modu
les\lodash._createpadding\index.js:9:14)
    at Module._compile (module.js:426:26)
    at Object.Module._extensions..js (module.js:444:10)
    at Module.load (module.js:351:32)
    at Function.Module._load (module.js:306:12)
    at Module.require (module.js:361:17)
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files\\iojs\\node.exe" "C:\\Program Files\\iojs\\node_modules\\npm\\bin\\npm-cli.js" "install
" "grunt-node-inspector" "--save-dev"
npm ERR! node v2.2.1
npm ERR! npm  v2.11.0
npm ERR! code ELIFECYCLE

npm ERR! v8-debug@0.4.6 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the v8-debug@0.4.6 install script 'node-pre-gyp install --fallback-to-build'.
npm ERR! This is most likely a problem with the v8-debug package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get their info via:
npm ERR!     npm owner ls v8-debug
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     D:\buzz\Projetos\mobtag_lab\npm-debug.log

**Comment by ChrisWren** [comment]
Looks like a nested dependency failed in `lodash._createpadding`. I would reach out to the maintainer of that module.
