### ISSUE TITLE
Not Supported on node version 8.x.x

### ISSUE THREAD

**Issue by ravishankarkumar** [ChrisWren/grunt-node-inspector#42]
npm install fails for node v8.9.0

Adding the console error
```Ravis-MacBook-Pro:delete ravishankar$ npm i grunt-node-inspector

> v8-debug@1.0.1 preinstall /Users/ravishankar/Desktop/delete/node_modules/v8-debug
> node -e 'process.exit(0)'


> v8-debug@1.0.1 install /Users/ravishankar/Desktop/delete/node_modules/v8-debug
> node-pre-gyp install --fallback-to-build

node-pre-gyp ERR! Tried to download(404): https://node-inspector.s3.amazonaws.com/debug/v1.0.1/node-v57-darwin-x64.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for v8-debug@1.0.1 and node@8.9.0 (node-v57 ABI, unknown) (falling back to source compile with node-gyp) 
  CXX(target) Release/obj.target/debug/src/debug.o
../src/debug.cc:41:20: warning: 'Call' is deprecated [-Wdeprecated-declarations]
        v8::Debug::Call(context, fn);
                   ^
/Users/ravishankar/.node-gyp/8.9.0/include/node/v8-debug.h:192:3: note: 'Call' has been explicitly marked deprecated here
  V8_DEPRECATED("No longer supported",
  ^
/Users/ravishankar/.node-gyp/8.9.0/include/node/v8config.h:321:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
../src/debug.cc:52:45: warning: 'GetDebugContext' is deprecated [-Wdeprecated-declarations]
        Isolate* debug_isolate = v8::Debug::GetDebugContext(Isolate::GetCurrent())->GetIsolate();
                                            ^
/Users/ravishankar/.node-gyp/8.9.0/include/node/v8-debug.h:208:3: note: 'GetDebugContext' has been explicitly marked deprecated here
  V8_DEPRECATED("Use v8-inspector",
  ^
/Users/ravishankar/.node-gyp/8.9.0/include/node/v8config.h:321:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
../src/debug.cc:57:20: warning: 'SendCommand' is deprecated [-Wdeprecated-declarations]
        v8::Debug::SendCommand(debug_isolate, *command, command.length());
                   ^
/Users/ravishankar/.node-gyp/8.9.0/include/node/v8-debug.h:169:3: note: 'SendCommand' has been explicitly marked deprecated here
  V8_DEPRECATED("No longer supported",
  ^
/Users/ravishankar/.node-gyp/8.9.0/include/node/v8config.h:321:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
../src/debug.cc:71:51: warning: 'GetDebugContext' is deprecated [-Wdeprecated-declarations]
        Local<Context> debug_context = v8::Debug::GetDebugContext(Isolate::GetCurrent());
                                                  ^
/Users/ravishankar/.node-gyp/8.9.0/include/node/v8-debug.h:208:3: note: 'GetDebugContext' has been explicitly marked deprecated here
  V8_DEPRECATED("Use v8-inspector",
  ^
/Users/ravishankar/.node-gyp/8.9.0/include/node/v8config.h:321:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
../src/debug.cc:78:22: error: no member named 'GetMirror' in 'v8::Debug'
          v8::Debug::GetMirror(info.GetIsolate()->GetCurrentContext(), info[0]);
          ~~~~~~~~~~~^
../src/debug.cc:80:38: warning: 'GetDebugContext' is deprecated [-Wdeprecated-declarations]
          debug_context = v8::Debug::GetDebugContext(Isolate::GetCurrent());
                                     ^
/Users/ravishankar/.node-gyp/8.9.0/include/node/v8-debug.h:208:3: note: 'GetDebugContext' has been explicitly marked deprecated here
  V8_DEPRECATED("Use v8-inspector",
  ^
/Users/ravishankar/.node-gyp/8.9.0/include/node/v8config.h:321:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
5 warnings and 1 error generated.
make: *** [Release/obj.target/debug/src/debug.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/ravishankar/.nvm/versions/node/v8.9.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Darwin 17.0.0
gyp ERR! command "/Users/ravishankar/.nvm/versions/node/v8.9.0/bin/node" "/Users/ravishankar/.nvm/versions/node/v8.9.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/Users/ravishankar/Desktop/delete/node_modules/v8-debug/build/debug/v1.0.1/node-v57-darwin-x64/debug.node" "--module_name=debug" "--module_path=/Users/ravishankar/Desktop/delete/node_modules/v8-debug/build/debug/v1.0.1/node-v57-darwin-x64"
gyp ERR! cwd /Users/ravishankar/Desktop/delete/node_modules/v8-debug
gyp ERR! node -v v8.9.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/Users/ravishankar/.nvm/versions/node/v8.9.0/bin/node /Users/ravishankar/.nvm/versions/node/v8.9.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/Users/ravishankar/Desktop/delete/node_modules/v8-debug/build/debug/v1.0.1/node-v57-darwin-x64/debug.node --module_name=debug --module_path=/Users/ravishankar/Desktop/delete/node_modules/v8-debug/build/debug/v1.0.1/node-v57-darwin-x64' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Users/ravishankar/Desktop/delete/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:126:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:925:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
node-pre-gyp ERR! System Darwin 17.0.0
node-pre-gyp ERR! command "/Users/ravishankar/.nvm/versions/node/v8.9.0/bin/node" "/Users/ravishankar/Desktop/delete/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /Users/ravishankar/Desktop/delete/node_modules/v8-debug
node-pre-gyp ERR! node -v v8.9.0
node-pre-gyp ERR! node-pre-gyp -v v0.6.39
node-pre-gyp ERR! not ok 
Failed to execute '/Users/ravishankar/.nvm/versions/node/v8.9.0/bin/node /Users/ravishankar/.nvm/versions/node/v8.9.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/Users/ravishankar/Desktop/delete/node_modules/v8-debug/build/debug/v1.0.1/node-v57-darwin-x64/debug.node --module_name=debug --module_path=/Users/ravishankar/Desktop/delete/node_modules/v8-debug/build/debug/v1.0.1/node-v57-darwin-x64' (1)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! v8-debug@1.0.1 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the v8-debug@1.0.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/ravishankar/.npm/_logs/2017-11-04T07_37_36_883Z-debug.log
```

Node version: 8.9.0
npm version: 5.5.1
OS: macOS High Sierra, version 10.13

**Comment by claudiopetrini** [comment]
Any update on this?

**Comment by amejiarosario** [comment]
Having the same issue on node v10

**Comment by Kiina** [comment]
Node-inspector won't work in anything higher then node 6, because the new tools build into node make it mostly useless. I would suggest you throw it out of your project and use the new devtools

https://medium.com/@paul_irish/debugging-node-js-nightlies-with-chrome-devtools-7c4a1b95ae27

**Comment by pavanmehta91** [comment]
@Kiina how do we use this with Grunt tasks?
